name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test main
      id: test-main
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test main
        setup-command: ''
        command: gradle test --tests *TestCoincidencia
        timeout: 10
        max-score: 25
    - name: Test constructores
      id: test-constructores
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test constructores
        setup-command: ''
        command: gradle test --tests *TestConstructor
        timeout: 10
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-MAIN_RESULTS: "${{steps.test-main.outputs.result}}"
        TEST-CONSTRUCTORES_RESULTS: "${{steps.test-constructores.outputs.result}}"
      with:
        runners: test-main,test-constructores
